require 'spaceship'
require "json"

import "FaslaneUpload.rb"
import "FastfileTest"
import "BuildTypeFactory.rb"
import "Enterprise/Types/Client/Client.rb"
import "Enterprise/Types/Debug/Debug.rb"
import "Store/Store.rb"

platform :ios do
    before_all do
        set_device_family()
        install_awscli_if_needed()
    end

    lane :post_zapptool do
        BuildTypeFactory.new.create.prepare_environment()
    end

    lane :validate_app_signing do
        BuildTypeFactory.new.create.perform_signing_validation()
    end

    lane :build do
        BuildTypeFactory.new.create.build
    end
    
    lane :create_provisioning_profile do |options|
        sigh(
            username: options[:username],
            app_identifier: options[:app_identifier],
            team_id: options[:team_id],
            provisioning_name: options[:provisioning_name],
            cert_owner_name: options[:cert_owner_name],
            filename: options[:filename],
            platform: options[:platform]
        )

        save_param_to_file("#{options[:app_identifier]}_PROFILE_UDID", "#{lane_context[SharedValues::SIGH_UUID]}")
    end
end

def set_device_family()
    puts("Setting device family param")
  
    device_family = ENV["device_target"]
    ENV["DEVICE_FAMILY"] = "1,2"
    if device_family == "iphone"
        ENV["DEVICE_FAMILY"] = "1"
    end
    if device_family == "ipad"
        ENV["DEVICE_FAMILY"] = "2"
    end
  end
  
def install_awscli_if_needed()
    envHelper = EnvironmentHelper.new
    unless envHelper.bundle_identifier.to_s.strip.empty?          
        if envHelper.isTvOS
            puts("Installing S3 AWS")
            sh("sudo pip install awscli")
        end
    end
end

def save_param_to_file(name, value)
    folder_name = "#{ENV['PWD']}/.fastlane_params"
    filename = "#{folder_name}/#{name}"
    Dir.mkdir(folder_name) unless File.exists?(folder_name)
    File.open(filename,"w") do |f|
       f.write(value)
    end
end

