# Uncomment the next line to define a global platform for your project
platform :tvos, '11.0'
require_relative './node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../scripts/autolink-react-dependencies.rb'

require 'resolv-replace'
install! 'cocoapods', :deterministic_uuids => false, :preserve_pod_file_structure => true
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'https://cdn.cocoapods.org/'

# Zaptool sources - Do not remove or change.

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

puts("\n\nCocoaPods preparing for platform: tvOS\n\n")

def shared_pods
    pod 'ZappCore', '= 0.9.16'
    pod 'ZappApple', '= 0.7.18'
    pod 'QuickBrickApple', :path => './node_modules/@applicaster/quick-brick-native-apple/QuickBrickApple.podspec'
    # Zaptool pods - Do not remove or change.

end

target 'ZappTvOS' do
  shared_pods
	use_react_native!(path: "./node_modules/react-native-tvos")

end

target 'ZappTvOSTests' do
  inherit! :search_paths
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['APPLICATION_TARGET'] = "ZappTvOS"
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['OTHER_CFLAGS'] = ['$(inherited)', "-fembed-bitcode"]
            config.build_settings['BITCODE_GENERATION_MODE']  = "bitcode"
						# This works around a unit test issue introduced in Xcode 10.
            # We only apply it to the Debug configuration to avoid bloating the app size
            if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
						end
        end
    end
end
